/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const ConsultationType = IDL.Variant({
  'clinicVisit' : IDL.Null,
  'online' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'contactInfo' : IDL.Text,
  'dateSubmitted' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'timestamp' : Time,
  'patientName' : IDL.Text,
  'isNew' : IDL.Bool,
  'healthConcerns' : IDL.Text,
  'consultationType' : ConsultationType,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PatientStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const PatientDetails = IDL.Record({
  'status' : Status,
  'appointmentCount' : IDL.Nat,
  'contactInfo' : ContactInfo,
  'lastVisitStatus' : PatientStatus,
  'name' : IDL.Text,
  'lastAppointmentTimestamp' : Time,
  'mostRecentAppointmentDate' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Record({
    'serviceTypeName' : IDL.Text,
    'serviceTypePrice' : IDL.Float64,
  }),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DoctorProfile = IDL.Record({
  'contactInfo' : ContactInfo,
  'name' : IDL.Text,
  'biography' : IDL.Text,
  'qualifications' : IDL.Text,
  'philosophy' : IDL.Text,
});
export const EmailNotificationSettings = IDL.Record({
  'isEnabled' : IDL.Bool,
  'recipientEmail' : IDL.Text,
});
export const HomePage = IDL.Record({ 'headline' : IDL.Text });
export const Inquiry = IDL.Record({
  'contactInfo' : IDL.Text,
  'dateSubmitted' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
});
export const PaymentMethod = IDL.Record({
  'method' : IDL.Text,
  'number' : IDL.Text,
  'upiId' : IDL.Text,
});
export const PaymentDetails = IDL.Record({
  'methods' : IDL.Vec(PaymentMethod),
  'email' : IDL.Text,
  'currency' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'dateSubmitted' : IDL.Text,
  'message' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'disableEmailNotifications' : IDL.Func([IDL.Null], [], []),
  'enableEmailNotifications' : IDL.Func([IDL.Null], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllPatientDetails' : IDL.Func([], [IDL.Vec(PatientDetails)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctorProfile' : IDL.Func([], [DoctorProfile], ['query']),
  'getEmailSettings' : IDL.Func([], [EmailNotificationSettings], ['query']),
  'getHomePage' : IDL.Func([], [HomePage], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getNewAppointmentsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPaymentDetails' : IDL.Func([], [PaymentDetails], ['query']),
  'getSortedPatientDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PatientDetails)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAppointmentsAsViewed' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPatientDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PatientDetails)],
      ['query'],
    ),
  'submitAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const ConsultationType = IDL.Variant({
    'clinicVisit' : IDL.Null,
    'online' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'contactInfo' : IDL.Text,
    'dateSubmitted' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'timestamp' : Time,
    'patientName' : IDL.Text,
    'isNew' : IDL.Bool,
    'healthConcerns' : IDL.Text,
    'consultationType' : ConsultationType,
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PatientStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const PatientDetails = IDL.Record({
    'status' : Status,
    'appointmentCount' : IDL.Nat,
    'contactInfo' : ContactInfo,
    'lastVisitStatus' : PatientStatus,
    'name' : IDL.Text,
    'lastAppointmentTimestamp' : Time,
    'mostRecentAppointmentDate' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Record({
      'serviceTypeName' : IDL.Text,
      'serviceTypePrice' : IDL.Float64,
    }),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DoctorProfile = IDL.Record({
    'contactInfo' : ContactInfo,
    'name' : IDL.Text,
    'biography' : IDL.Text,
    'qualifications' : IDL.Text,
    'philosophy' : IDL.Text,
  });
  const EmailNotificationSettings = IDL.Record({
    'isEnabled' : IDL.Bool,
    'recipientEmail' : IDL.Text,
  });
  const HomePage = IDL.Record({ 'headline' : IDL.Text });
  const Inquiry = IDL.Record({
    'contactInfo' : IDL.Text,
    'dateSubmitted' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
  });
  const PaymentMethod = IDL.Record({
    'method' : IDL.Text,
    'number' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const PaymentDetails = IDL.Record({
    'methods' : IDL.Vec(PaymentMethod),
    'email' : IDL.Text,
    'currency' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'dateSubmitted' : IDL.Text,
    'message' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'disableEmailNotifications' : IDL.Func([IDL.Null], [], []),
    'enableEmailNotifications' : IDL.Func([IDL.Null], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllPatientDetails' : IDL.Func([], [IDL.Vec(PatientDetails)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctorProfile' : IDL.Func([], [DoctorProfile], ['query']),
    'getEmailSettings' : IDL.Func([], [EmailNotificationSettings], ['query']),
    'getHomePage' : IDL.Func([], [HomePage], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getNewAppointmentsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaymentDetails' : IDL.Func([], [PaymentDetails], ['query']),
    'getSortedPatientDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PatientDetails)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAppointmentsAsViewed' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPatientDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PatientDetails)],
        ['query'],
      ),
    'submitAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };