/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : Status,
  'contactInfo' : string,
  'dateSubmitted' : string,
  'preferredDateTime' : string,
  'timestamp' : Time,
  'patientName' : string,
  'isNew' : boolean,
  'healthConcerns' : string,
  'consultationType' : ConsultationType,
}
export type ConsultationType = { 'clinicVisit' : null } |
  { 'online' : null };
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DoctorProfile {
  'contactInfo' : ContactInfo,
  'name' : string,
  'biography' : string,
  'qualifications' : string,
  'philosophy' : string,
}
export interface EmailNotificationSettings {
  'isEnabled' : boolean,
  'recipientEmail' : string,
}
export interface HomePage { 'headline' : string }
export interface Inquiry {
  'contactInfo' : string,
  'dateSubmitted' : string,
  'name' : string,
  'message' : string,
}
export interface PatientDetails {
  'status' : Status,
  'appointmentCount' : bigint,
  'contactInfo' : ContactInfo,
  'lastVisitStatus' : PatientStatus,
  'name' : string,
  'lastAppointmentTimestamp' : Time,
  'mostRecentAppointmentDate' : string,
}
export type PatientStatus = { 'active' : null } |
  { 'inactive' : null };
export interface PaymentDetails {
  'methods' : Array<PaymentMethod>,
  'email' : string,
  'currency' : string,
}
export interface PaymentMethod {
  'method' : string,
  'number' : string,
  'upiId' : string,
}
export interface Service {
  'id' : bigint,
  'serviceType' : { 'serviceTypeName' : string, 'serviceTypePrice' : number },
  'name' : string,
  'description' : string,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Testimonial {
  'dateSubmitted' : string,
  'message' : string,
  'patientName' : string,
  'rating' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomService' : ActorMethod<[string, string, string, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'disableEmailNotifications' : ActorMethod<[null], undefined>,
  'enableEmailNotifications' : ActorMethod<[null], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllPatientDetails' : ActorMethod<[], Array<PatientDetails>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctorProfile' : ActorMethod<[], DoctorProfile>,
  'getEmailSettings' : ActorMethod<[], EmailNotificationSettings>,
  'getHomePage' : ActorMethod<[], HomePage>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getNewAppointmentsCount' : ActorMethod<[], bigint>,
  'getPaymentDetails' : ActorMethod<[], PaymentDetails>,
  'getSortedPatientDetails' : ActorMethod<[bigint], Array<PatientDetails>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAppointmentsAsViewed' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPatientDetails' : ActorMethod<[string], Array<PatientDetails>>,
  'submitAppointment' : ActorMethod<[Appointment], bigint>,
  'submitInquiry' : ActorMethod<[Inquiry], undefined>,
  'submitTestimonial' : ActorMethod<[Testimonial], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointmentStatus' : ActorMethod<
    [
      bigint,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];