/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Appointment {
    id: bigint;
    status: Status;
    contactInfo: string;
    dateSubmitted: string;
    preferredDateTime: string;
    timestamp: Time;
    patientName: string;
    isNew: boolean;
    healthConcerns: string;
    consultationType: ConsultationType;
}
export type Time = bigint;
export interface PaymentMethod {
    method: string;
    number: string;
    upiId: string;
}
export interface DoctorProfile {
    contactInfo: ContactInfo;
    name: string;
    biography: string;
    qualifications: string;
    philosophy: string;
}
export interface Service {
    id: bigint;
    serviceType: {
        serviceTypeName: string;
        serviceTypePrice: number;
    };
    name: string;
    description: string;
}
export interface EmailNotificationSettings {
    isEnabled: boolean;
    recipientEmail: string;
}
export interface PatientDetails {
    status: Status;
    appointmentCount: bigint;
    contactInfo: ContactInfo;
    lastVisitStatus: PatientStatus;
    name: string;
    lastAppointmentTimestamp: Time;
    mostRecentAppointmentDate: string;
}
export interface HomePage {
    headline: string;
}
export interface PaymentDetails {
    methods: Array<PaymentMethod>;
    email: string;
    currency: string;
}
export interface Inquiry {
    contactInfo: string;
    dateSubmitted: string;
    name: string;
    message: string;
}
export interface ContactInfo {
    email: string;
    address: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Testimonial {
    dateSubmitted: string;
    message: string;
    patientName: string;
    rating: number;
}
export enum ConsultationType {
    clinicVisit = "clinicVisit",
    online = "online"
}
export enum PatientStatus {
    active = "active",
    inactive = "inactive"
}
export enum Status {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export interface backendInterface {
    addCustomService(name: string, description: string, serviceTypeName: string, serviceTypePrice: number): Promise<void>;
    deleteService(id: bigint): Promise<void>;
    disableEmailNotifications(arg0: null): Promise<void>;
    enableEmailNotifications(arg0: null): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllPatientDetails(): Promise<Array<PatientDetails>>;
    getAllServices(): Promise<Array<Service>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getDoctorProfile(): Promise<DoctorProfile>;
    getEmailSettings(): Promise<EmailNotificationSettings>;
    getHomePage(): Promise<HomePage>;
    getInquiries(): Promise<Array<Inquiry>>;
    getNewAppointmentsCount(): Promise<bigint>;
    getPaymentDetails(): Promise<PaymentDetails>;
    getSortedPatientDetails(sortBy: bigint): Promise<Array<PatientDetails>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(caller: Principal): Promise<boolean>;
    markAppointmentsAsViewed(): Promise<void>;
    removeAdmin(target: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPatientDetails(searchTerm: string): Promise<Array<PatientDetails>>;
    setAdmin(target: Principal): Promise<void>;
    submitAppointment(newAppointment: Appointment): Promise<bigint>;
    submitInquiry(inquiry: Inquiry): Promise<void>;
    submitTestimonial(testimonial: Testimonial): Promise<void>;
    updateAppointmentStatus(id: bigint, status: Status): Promise<void>;
    updateService(id: bigint, updatedService: Service): Promise<void>;
}
import type { Appointment as _Appointment, ConsultationType as _ConsultationType, ContactInfo as _ContactInfo, PatientDetails as _PatientDetails, PatientStatus as _PatientStatus, Status as _Status, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomService(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async disableEmailNotifications(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableEmailNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableEmailNotifications(arg0);
            return result;
        }
    }
    async enableEmailNotifications(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableEmailNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableEmailNotifications(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatientDetails(): Promise<Array<PatientDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientDetails();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientDetails();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorProfile(): Promise<DoctorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorProfile();
            return result;
        }
    }
    async getEmailSettings(): Promise<EmailNotificationSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailSettings();
            return result;
        }
    }
    async getHomePage(): Promise<HomePage> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomePage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomePage();
            return result;
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return result;
        }
    }
    async getNewAppointmentsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewAppointmentsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewAppointmentsCount();
            return result;
        }
    }
    async getPaymentDetails(): Promise<PaymentDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentDetails();
            return result;
        }
    }
    async getSortedPatientDetails(arg0: bigint): Promise<Array<PatientDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedPatientDetails(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedPatientDetails(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin(arg0);
            return result;
        }
    }
    async markAppointmentsAsViewed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAppointmentsAsViewed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAppointmentsAsViewed();
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchPatientDetails(arg0: string): Promise<Array<PatientDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatientDetails(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatientDetails(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async submitAppointment(arg0: Appointment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointment(to_candid_Appointment_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointment(to_candid_Appointment_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitInquiry(arg0: Inquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return result;
        }
    }
    async submitTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationType): ConsultationType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PatientDetails_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientDetails): PatientDetails {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PatientStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientStatus): PatientStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    appointmentCount: bigint;
    contactInfo: _ContactInfo;
    lastVisitStatus: _PatientStatus;
    name: string;
    lastAppointmentTimestamp: _Time;
    mostRecentAppointmentDate: string;
}): {
    status: Status;
    appointmentCount: bigint;
    contactInfo: ContactInfo;
    lastVisitStatus: PatientStatus;
    name: string;
    lastAppointmentTimestamp: Time;
    mostRecentAppointmentDate: string;
} {
    return {
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        appointmentCount: value.appointmentCount,
        contactInfo: value.contactInfo,
        lastVisitStatus: from_candid_PatientStatus_n11(_uploadFile, _downloadFile, value.lastVisitStatus),
        name: value.name,
        lastAppointmentTimestamp: value.lastAppointmentTimestamp,
        mostRecentAppointmentDate: value.mostRecentAppointmentDate
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    contactInfo: string;
    dateSubmitted: string;
    preferredDateTime: string;
    timestamp: _Time;
    patientName: string;
    isNew: boolean;
    healthConcerns: string;
    consultationType: _ConsultationType;
}): {
    id: bigint;
    status: Status;
    contactInfo: string;
    dateSubmitted: string;
    preferredDateTime: string;
    timestamp: Time;
    patientName: string;
    isNew: boolean;
    healthConcerns: string;
    consultationType: ConsultationType;
} {
    return {
        id: value.id,
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        dateSubmitted: value.dateSubmitted,
        preferredDateTime: value.preferredDateTime,
        timestamp: value.timestamp,
        patientName: value.patientName,
        isNew: value.isNew,
        healthConcerns: value.healthConcerns,
        consultationType: from_candid_ConsultationType_n6(_uploadFile, _downloadFile, value.consultationType)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): PatientStatus {
    return "active" in value ? PatientStatus.active : "inactive" in value ? PatientStatus.inactive : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): Status {
    return "cancelled" in value ? Status.cancelled : "pending" in value ? Status.pending : "completed" in value ? Status.completed : "confirmed" in value ? Status.confirmed : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clinicVisit: null;
} | {
    online: null;
}): ConsultationType {
    return "clinicVisit" in value ? ConsultationType.clinicVisit : "online" in value ? ConsultationType.online : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientDetails>): Array<PatientDetails> {
    return value.map((x)=>from_candid_PatientDetails_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Appointment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ConsultationType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationType): _ConsultationType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status;
    contactInfo: string;
    dateSubmitted: string;
    preferredDateTime: string;
    timestamp: Time;
    patientName: string;
    isNew: boolean;
    healthConcerns: string;
    consultationType: ConsultationType;
}): {
    id: bigint;
    status: _Status;
    contactInfo: string;
    dateSubmitted: string;
    preferredDateTime: string;
    timestamp: _Time;
    patientName: string;
    isNew: boolean;
    healthConcerns: string;
    consultationType: _ConsultationType;
} {
    return {
        id: value.id,
        status: to_candid_Status_n16(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        dateSubmitted: value.dateSubmitted,
        preferredDateTime: value.preferredDateTime,
        timestamp: value.timestamp,
        patientName: value.patientName,
        isNew: value.isNew,
        healthConcerns: value.healthConcerns,
        consultationType: to_candid_ConsultationType_n18(_uploadFile, _downloadFile, value.consultationType)
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == Status.cancelled ? {
        cancelled: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationType): {
    clinicVisit: null;
} | {
    online: null;
} {
    return value == ConsultationType.clinicVisit ? {
        clinicVisit: null
    } : value == ConsultationType.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
